version: "3.9"

x-environment:
  moscow: &moscow-time
    TZ=Europe/Moscow

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - *moscow-time
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app

  rest:
    image: docker.stm/gov2022/app
    volumes:
      - .:/code
    environment:
      - *moscow-time
#    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    command: python main.py main:app 0.0.0.0 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true