version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./dockerfiles/postgres/init/create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app

  rest:
    image: app
    volumes:
      - .:/code
#    command: alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    command: python main.py
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true